{
    AlgChe.i.m
    AlgCheMult.i.m
    AlgCheRes.i.m
    AlgCheResMult.i.m
    Parameters.i.m
    RRCATools.i.m
    RepTheory.i.m
		RepTheory2.i.m
    Poisson.i.m
    GordonDB.i.m
    Families.i.m
    RigidRepresentations.i.m
    Center.i.m
    SymplecticDoubling.i.m
    CellularCharacters.i.m
    CenterPresentation.i.m
		EulerFamilies.i.m
		SymplecticLeaves.i.m
		CheCoeff.i.m
		Supersingular.i.m
		Cuspidal.i.m
		BlockGraph.i.m
    MartinoConjecture.i.m
}
