{
  +../AffineAlgebras/AffineAlgebras.s.m
  +../AlgebraicGeometry/AlgebraicGeometry.s.m
  +../Algebras/Algebras.s.m
  CHAMP.i.m
  +../Cherednik/Cherednik.s.m
  +../Combinatorics/Combinatorics.s.m
  +../DB/DB.s.m
  +../Extensions/Extensions.s.m
  +../GroupRepresentations/GroupRepresentations.s.m
  +../Groups/Groups.s.m
  +../HTML/HTML.s.m
  +../Lusztig/Lusztig.s.m
  +../Matrices/Matrices.s.m
  +../MatrixGroups/MatrixGroups.s.m
  +../ModFinder/ModFinder.s.m
  +../Modules/Modules.s.m
  +../ReflectionGroups/ReflectionGroups.s.m
  +../System/System.s.m
}
